name: Run .NET Tests on PR

on:
  pull_request:
    branches:
      - qa
      - main
      - develop
      - prod

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore Feex.sln

      - name: Build Solution
        run: dotnet build Feex.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test Feex.sln --configuration Release --no-restore --logger "trx"
